data:
  history_period: "1y"  # Period for historical data from yfinance
  display_period: "6mo"  # Period to display in graphs
tickers_file: "tickers.csv"
indicators:
  - name: "SMA_20"
    type: "sma"
    period: 20
  - name: "SMA_50"
    type: "sma"
    period: 50
  - name: "SMA_DIFF"
    type: "sma_diff"
    short_sma: "SMA_20"
    long_sma: "SMA_50"
    rank: true  # Include in ranking
  - name: "RSI"
    type: "rsi"
    period: 14
    rank: true
  - name: "MACD"
    type: "macd"
    fast_period: 12
    slow_period: 26
    signal_period: 9