data:
  history_period: "5y"
  display_period: "5y"
  n_mad: 20
  n_mad_filter: 5
tickers_file: "tickers/tickers_lists.csv"
fundamentals:
  - name: earningsGrowth
    cluster: Growth
    order: High
  - name: revenueGrowth
    cluster: Growth
    order: High
  - name: profitMargins
    cluster: Quality
    order: High
  - name: grossMargins
    cluster: Quality
    order: High
  - name: returnOnEquity
    cluster: Quality
    order: High
  - name: returnOnAssets
    cluster: Quality
    order: High
  - name: debtToEquity
    cluster: Value
    order: Low
  - name: priceToBook
    cluster: Value
    order: Low
  - name: forwardPE
    cluster: Value
    order: Low
  - name: dividendYield
    cluster: Value
    order: High
extra_fundamental_fields:
  - longName
  - sector
  - longBusinessSummary
indicators:
  - name: "Close"
    type: "sma"
    period: 1
    filter: false
    panel: price
    cluster: null
    order: null
  - name: "SMA_10"
    type: "sma"
    period: 10
    filter: false
    panel: price
    cluster: null
    order: null
  - name: "SMA_40"
    type: "sma"
    period: 40
    filter: false
    panel: price
    cluster: null
    order: null
  - name: "SMA_120"
    type: "sma"
    period: 120
    filter: false
    panel: price
    cluster: null
    order: null
  - name: "Close_10_%_D"
    type: "sma_diff"
    short_sma: "Close"
    long_sma: "SMA_10"
    filter: true
    panel: middle
    cluster: Momentum
    order: High
  - name: "10_40_%_D"
    type: "sma_diff"
    short_sma: "SMA_10"
    long_sma: "SMA_40"
    filter: true
    panel: middle
    cluster: Momentum
    order: High
  - name: "40_120_%_D"
    type: "sma_diff"
    short_sma: "SMA_40"
    long_sma: "SMA_120"
    filter: true
    panel: middle
    cluster: Momentum
    order: High
  - name: "RSI_3_months"
    type: "rsi"
    period: 90
    filter: true
    panel: lower
    cluster: Momentum
    order: High
explanations:
  fundamentals:
    earningsGrowth: "Year-over-year earnings growth rate."
    revenueGrowth: "Year-over-year revenue growth rate."
    profitMargins: "Net profit as a percentage of revenue."
    grossMargins: "Gross profit as a percentage of revenue."
    returnOnEquity: "Net income divided by shareholders' equity."
    debtToEquity: "Total debt divided by shareholders' equity."
    priceToBook: "Share price divided by book value per share."
    forwardPE: "Forward price-to-earnings ratio."
  indicators:
    Close: "Closing price."
    SMA_10: "Simple Moving Average over 10 days."
    SMA_40: "Simple Moving Average over 40 days."
    SMA_120: "Simple Moving Average over 120 days."
    Close_10_%_D: "Percent difference between Close and SMA_10."
    10_40_%_D: "Percent difference between SMA_10 and SMA_40."
    40_120_%_D: "Percent difference between SMA_40 and SMA_120."
    RSI: "Relative Strength Index (6 months)."