data:
  history_period: "2y"
  display_period: "1y"
tickers_file: "tickers.csv"
indicators:
  - name: "SMA_20"
    type: "sma"
    period: 20
    filter: false
    panel: price
  - name: "SMA_50"
    type: "sma"
    period: 50
    filter: false
    panel: price
  - name: "SMA_DIFF"
    type: "sma_diff"
    short_sma: "SMA_20"
    long_sma: "SMA_50"
    filter: true
    panel: middle
  - name: "RSI"
    type: "rsi"
    period: 14
    filter: true
    panel: lower