data:
  history_period: "3y"
  display_period: "2y"
  n_mad: 20
  n_mad_filter: 5
tickers_file: "tickers/tickers_lists.csv"
fundamentals:
  - earningsGrowth
  - revenueGrowth
  - profitMargins
  - grossMargins
  - returnOnEquity
  - debtToEquity
  - priceToBook
  - forwardPE
extra_fundamental_fields:
  - longName
  - sector
  - longBusinessSummary
indicators:
  - name: "Close"
    type: "sma"
    period: 1
    filter: false
    panel: price
  - name: "SMA_10"
    type: "sma"
    period: 10
    filter: false
    panel: price
  - name: "SMA_40"
    type: "sma"
    period: 40
    filter: false
    panel: price
  - name: "SMA_120"
    type: "sma"
    period: 120
    filter: false
    panel: price
  - name: "Close_10_%_D"
    type: "sma_diff"
    short_sma: "Close"
    long_sma: "SMA_10"
    filter: true
    panel: middle
  - name: "10_40_%_D"
    type: "sma_diff"
    short_sma: "SMA_10"
    long_sma: "SMA_40"
    filter: true
    panel: middle
  - name: "40_120_%_D"
    type: "sma_diff"
    short_sma: "SMA_40"
    long_sma: "SMA_120"
    filter: true
    panel: middle
  - name: "RSI"
    type: "rsi"
    period: 14
    filter: true
    panel: lower