# Inställningar för in- och utdata
output_path: "csv-data"
input_ticker_file: "tickers/tickers_lists.csv"
output_file_path: "csv-data/stock_evaluation_results.csv"
price_data_file: "price_data.csv"

# Inställningar för datainhämtning
data_fetch_years: 4

# Inställningar för glidande medelvärden
SMA_short: 10
SMA_medium: 50
SMA_long: 200

# Inställningar för pct diff från senaste slutkurs
pct_diff_short: 20
pct_diff_medium: 90
pct_diff_long: 200

# CAGR inställningar
cagr_dimension:
  - "Total Revenue"
  - "EBITDA"
  - "Basic EPS"


# Definitioner av nyckeltal och deras källor/logik
ratio_definitions:
  ROE:
    formula: "Net_Income / Stockholders_Equity"
    source_income: ["Net Income"]
    source_bs: ["Stockholders Equity"]
    higher_is_better: True
  ROIC:
    formula: "(EBIT * (1 - (Tax_Provision / Pretax_Income))) / (Total_Debt + Stockholders_Equity)"
    source_income: ["EBIT", "Tax Provision", "Pretax Income"]
    source_bs: ["Total Debt", "Stockholders Equity"]
    higher_is_better: True
  Soliditet:
    formula: "Stockholders_Equity / Total_Assets"
    source_bs: ["Stockholders Equity", "Total Assets"]
    higher_is_better: True
  Skuldsättningsgrad:
    formula: "Total_Debt / Stockholders_Equity"
    source_bs: ["Total Debt", "Stockholders Equity"]
    higher_is_better: False
  Räntetäckningsgrad:
    formula: "EBIT / Interest_Expense"
    source_income: ["EBIT", "Interest Expense"]
    higher_is_better: True
  Bruttomarginal:
    formula: "Gross_Profit / Total_Revenue"
    source_income: ["Gross Profit", "Total Revenue"]
    higher_is_better: True
  Rörelsemarginal:
    formula: "Operating_Income / Total_Revenue"
    source_income: ["Operating Income", "Total Revenue"]
    higher_is_better: True
  Vinstmarginal:
    formula: "Net_Income / Total_Revenue"
    source_income: ["Net Income", "Total Revenue"]
    higher_is_better: True
  PE_tal:
    formula: "currentPrice / Basic_EPS"
    source_stock: ["currentPrice"]
    source_income: ["Basic EPS"]
    higher_is_better: False
  PB_tal:
    formula: "currentPrice / (Stockholders_Equity / sharesOutstanding)"
    source_stock: ["currentPrice", "sharesOutstanding"]
    source_bs: ["Stockholders Equity"]
    higher_is_better: False
  EV_EBITDA:
    formula: "(currentPrice * sharesOutstanding + Total_Debt - Cash_And_Cash_Equivalents) / EBITDA"
    source_stock: ["currentPrice", "sharesOutstanding"]
    source_bs: ["Total Debt", "Cash And Cash Equivalents"]
    source_income: ["EBITDA"]
    higher_is_better: False
  Rörelseflödesmarginal:
    formula: "Operating_Cash_Flow / Total_Revenue"
    source_cf: ["Operating Cash Flow"]
    source_income: ["Total Revenue"]
    higher_is_better: True
  Fritt_Kassaflode_per_Aktie:
    formula: "Free_Cash_Flow / sharesOutstanding"
    source_cf: ["Free Cash Flow"]
    source_stock: ["sharesOutstanding"]
    higher_is_better: True
  Kassaflode_till_Skuld:
    formula: "Operating_Cash_Flow / Total_Debt"
    source_cf: ["Operating Cash Flow"]
    source_bs: ["Total Debt"]
    higher_is_better: True

# Konfiguration för rankningsmetoden
ranking_method:
  type: "percentile_hybrid_trend"
  trend_zero_threshold: 0.001

# Ratios i kategorier
category_ratios:
  Kvalitet_latest_ratioRank:
    ROE_latest_ratioRank: 1
    ROIC_latest_ratioRank: 1
  Kvalitet_trend_ratioRank:
    ROE_trend_ratioRank: 1
    ROIC_trend_ratioRank: 1
  FinansiellHalsa_latest_ratioRank:
    Soliditet_latest_ratioRank: 1
    Skuldsättningsgrad_latest_ratioRank: 1
    # Räntetäckningsgrad_latest_ratioRank: 1
  FinansiellHalsa_trend_ratioRank:
    Soliditet_trend_ratioRank: 1
    Skuldsättningsgrad_trend_ratioRank: 1
    # Räntetäckningsgrad_trend_ratioRank: 1
  Lonsamhet_latest_ratioRank:
    Bruttomarginal_latest_ratioRank: 1
    Rörelsemarginal_latest_ratioRank: 1
    Vinstmarginal_latest_ratioRank: 1
  Lonsamhet_trend_ratioRank:
    Bruttomarginal_trend_ratioRank: 1
    Rörelsemarginal_trend_ratioRank: 1
    Vinstmarginal_trend_ratioRank: 1
  Vardering_latest_ratioRank:
    PE_tal_latest_ratioRank: 1
    PB_tal_latest_ratioRank: 1
    EV_EBITDA_latest_ratioRank: 1
  Vardering_trend_ratioRank:
    PE_tal_trend_ratioRank: 1
    PB_tal_trend_ratioRank: 1
    EV_EBITDA_trend_ratioRank: 1
  Kassaflode_latest_ratioRank:
    # Rörelseflödesmarginal_latest_ratioRank: 1
    Fritt_Kassaflode_per_Aktie_latest_ratioRank: 1
    Kassaflode_till_Skuld_latest_ratioRank: 1
  Kassaflode_trend_ratioRank:
    # Rörelseflödesmarginal_trend_ratioRank: 1
    Fritt_Kassaflode_per_Aktie_trend_ratioRank: 1
    Kassaflode_till_Skuld_trend_ratioRank: 1

# Hjälptexter för nyckeltal (endast _latest_rank)
ratio_help_texts:
  ROE_latest_rank: "Avkastning på eget kapital (ROE) visar hur effektivt bolaget genererar vinst på aktieägarnas kapital. Ett högt ROE innebär att företaget är bra på att skapa vinst från de pengar som aktieägarna har satsat. Det är ett centralt nyckeltal för att bedöma lönsamheten och hur väl ledningen använder kapitalet. Högre värde är bättre, men det är också viktigt att jämföra med branschkollegor."
  ROIC_latest_rank: "Avkastning på investerat kapital (ROIC) mäter hur väl bolaget använder både eget och lånat kapital för att skapa vinst. Ett högt ROIC indikerar att företaget är effektivt på att generera avkastning på det totala kapitalet som används i verksamheten. Detta nyckeltal är särskilt användbart för att jämföra företag med olika kapitalstrukturer. Högre värde är bättre."
  Soliditet_latest_rank: "Soliditet visar hur stor andel av tillgångarna som är finansierade med eget kapital. En hög soliditet innebär att företaget har en stark finansiell ställning och är mindre beroende av lån, vilket minskar den finansiella risken. Soliditet är särskilt viktig i tider av ekonomisk osäkerhet. Hög soliditet innebär lägre finansiell risk."
  Skuldsättningsgrad_latest_rank: "Skuldsättningsgrad visar förhållandet mellan företagets skulder och eget kapital. En låg skuldsättningsgrad innebär att företaget har relativt lite skulder jämfört med sitt egna kapital, vilket minskar risken för betalningsproblem vid sämre tider. En hög skuldsättningsgrad kan innebära högre risk men också möjlighet till högre avkastning. Lägre värde innebär lägre finansiell risk."
  Räntetäckningsgrad_latest_rank: "Räntetäckningsgrad visar företagets förmåga att täcka sina räntekostnader med rörelseresultatet (EBIT). En hög räntetäckningsgrad innebär att företaget har god marginal för att betala sina räntekostnader, vilket minskar risken för finansiella problem. Detta är särskilt viktigt för företag med stora skulder. Högre värde är bättre."
  Bruttomarginal_latest_rank: "Bruttomarginal visar hur stor andel av omsättningen som återstår efter att produktionskostnaderna har dragits av. En hög bruttomarginal innebär att företaget har god kontroll över sina direkta kostnader och kan generera mer vinst från varje såld enhet. Detta nyckeltal är viktigt för att bedöma företagets prissättningsförmåga och kostnadskontroll. Högre värde är bättre."
  Rörelsemarginal_latest_rank: "Rörelsemarginal visar hur stor andel av omsättningen som återstår efter att alla rörelsekostnader har dragits av, men före räntor och skatt. En hög rörelsemarginal indikerar att företaget är effektivt på att kontrollera sina kostnader och generera vinst från den löpande verksamheten. Högre värde är bättre."
  Vinstmarginal_latest_rank: "Vinstmarginal visar hur stor andel av omsättningen som blir kvar som vinst efter alla kostnader, inklusive skatt och räntor. En hög vinstmarginal innebär att företaget är bra på att omvandla försäljning till vinst, vilket är ett tecken på god lönsamhet. Högre värde är bättre."
  PE_tal_latest_rank: "P/E-tal (pris/vinst-tal) visar hur aktien värderas i förhållande till företagets vinst per aktie. Ett lågt P/E-tal kan tyda på att aktien är lågt värderad, men det kan också bero på tillfälligt låg vinst. Det är viktigt att jämföra P/E-talet med liknande företag i samma bransch. Lägre värde kan innebära att aktien är billigare."
  PB_tal_latest_rank: "P/B-tal (pris/eget kapital-tal) visar hur aktien värderas i förhållande till företagets egna kapital per aktie. Ett lågt P/B-tal kan indikera att aktien är undervärderad, men det kan också bero på problem i verksamheten. Jämför alltid med branschkollegor för att få en rättvisande bild. Lägre värde kan innebära att aktien är billigare."
  EV_EBITDA_latest_rank: "EV/EBITDA (företagsvärde/rörelseresultat före avskrivningar) visar bolagets värdering i förhållande till dess rörelseresultat före avskrivningar. Ett lågt EV/EBITDA-tal kan tyda på att bolaget är lågt värderat i förhållande till sin intjäningsförmåga. Detta nyckeltal används ofta vid företagsvärderingar och jämförelser mellan bolag. Lägre värde kan innebära att aktien är billigare."
  Rörelseflödesmarginal_latest_rank: "Rörelseflödesmarginal visar hur stor andel av omsättningen som omvandlas till kassaflöde från den löpande verksamheten. En hög rörelseflödesmarginal innebär att företaget är bra på att generera kassaflöde från sin försäljning, vilket är viktigt för att kunna finansiera investeringar och utdelningar. Högre värde är bättre."
  Fritt_Kassaflode_per_Aktie_latest_rank: "Fritt kassaflöde per aktie visar hur mycket kassaflöde som genereras per aktie efter att investeringar har dragits av. Detta nyckeltal är viktigt för att bedöma företagets förmåga att skapa värde för aktieägarna och finansiera utdelningar eller återköp av aktier. Högre värde är bättre."
  Kassaflode_till_Skuld_latest_rank: "Kassaflöde till skuld visar företagets förmåga att betala av sina skulder med det kassaflöde som genereras från verksamheten. En hög kvot innebär att företaget snabbt kan minska sina skulder, vilket minskar den finansiella risken. Högre värde är bättre."
  ROE_trend_ratioRank: "Avkastning på eget kapital (ROE) visar hur effektivt bolaget genererar vinst på aktieägarnas kapital. Ett högt ROE innebär att företaget är bra på att skapa vinst från de pengar som aktieägarna har satsat. Det är ett centralt nyckeltal för att bedöma lönsamheten och hur väl ledningen använder kapitalet. Högre värde är bättre, men det är också viktigt att jämföra med branschkollegor."
  ROIC_trend_ratioRank: "Avkastning på investerat kapital (ROIC) mäter hur väl bolaget använder både eget och lånat kapital för att skapa vinst. Ett högt ROIC indikerar att företaget är effektivt på att generera avkastning på det totala kapitalet som används i verksamheten. Detta nyckeltal är särskilt användbart för att jämföra företag med olika kapitalstrukturer. Högre värde är bättre."
  Soliditet_trend_ratioRank: "Soliditet visar hur stor andel av tillgångarna som är finansierade med eget kapital. En hög soliditet innebär att företaget har en stark finansiell ställning och är mindre beroende av lån, vilket minskar den finansiella risken. Soliditet är särskilt viktig i tider av ekonomisk osäkerhet. Hög soliditet innebär lägre finansiell risk."
  Skuldsättningsgrad_trend_ratioRank: "Skuldsättningsgrad visar förhållandet mellan företagets skulder och eget kapital. En låg skuldsättningsgrad innebär att företaget har relativt lite skulder jämfört med sitt egna kapital, vilket minskar risken för betalningsproblem vid sämre tider. En hög skuldsättningsgrad kan innebära högre risk men också möjlighet till högre avkastning. Lägre värde innebär lägre finansiell risk."
  Räntetäckningsgrad_trend_ratioRank: "Räntetäckningsgrad visar företagets förmåga att täcka sina räntekostnader med rörelseresultatet (EBIT). En hög räntetäckningsgrad innebär att företaget har god marginal för att betala sina räntekostnader, vilket minskar risken för finansiella problem. Detta är särskilt viktigt för företag med stora skulder. Högre värde är bättre."
  Bruttomarginal_trend_ratioRank: "Bruttomarginal visar hur stor andel av omsättningen som återstår efter att produktionskostnaderna har dragits av. En hög bruttomarginal innebär att företaget har god kontroll över sina direkta kostnader och kan generera mer vinst från varje såld enhet. Detta nyckeltal är viktigt för att bedöma företagets prissättningsförmåga och kostnadskontroll. Högre värde är bättre."
  Rörelsemarginal_trend_ratioRank: "Rörelsemarginal visar hur stor andel av omsättningen som återstår efter att alla rörelsekostnader har dragits av, men före räntor och skatt. En hög rörelsemarginal indikerar att företaget är effektivt på att kontrollera sina kostnader och generera vinst från den löpande verksamheten. Högre värde är bättre."
  Vinstmarginal_trend_ratioRank: "Vinstmarginal visar hur stor andel av omsättningen som blir kvar som vinst efter alla kostnader, inklusive skatt och räntor. En hög vinstmarginal innebär att företaget är bra på att omvandla försäljning till vinst, vilket är ett tecken på god lönsamhet. Högre värde är bättre."
  PE_tal_trend_ratioRank: "P/E-tal (pris/vinst-tal) visar hur aktien värderas i förhållande till företagets vinst per aktie. Ett lågt P/E-tal kan tyda på att aktien är lågt värderad, men det kan också bero på tillfälligt låg vinst. Det är viktigt att jämföra P/E-talet med liknande företag i samma bransch. Lägre värde kan innebära att aktien är billigare."
  PB_tal_trend_ratioRank: "P/B-tal (pris/eget kapital-tal) visar hur aktien värderas i förhållande till företagets egna kapital per aktie. Ett lågt P/B-tal kan indikera att aktien är undervärderad, men det kan också bero på problem i verksamheten. Jämför alltid med branschkollegor för att få en rättvisande bild. Lägre värde kan innebära att aktien är billigare."
  EV_EBITDA_trend_ratioRank: "EV/EBITDA (företagsvärde/rörelseresultat före avskrivningar) visar bolagets värdering i förhållande till dess rörelseresultat före avskrivningar. Ett lågt EV/EBITDA-tal kan tyda på att bolaget är lågt värderat i förhållande till sin intjäningsförmåga. Detta nyckeltal används ofta vid företagsvärderingar och jämförelser mellan bolag. Lägre värde kan innebära att aktien är billigare."
  Rörelseflödesmarginal_trend_ratioRank: "Rörelseflödesmarginal visar hur stor andel av omsättningen som omvandlas till kassaflöde från den löpande verksamheten. En hög rörelseflödesmarginal innebär att företaget är bra på att generera kassaflöde från sin försäljning, vilket är viktigt för att kunna finansiera investeringar och utdelningar. Högre värde är bättre."
  Fritt_Kassaflode_per_Aktie_trend_ratioRank: "Fritt kassaflöde per aktie visar hur mycket kassaflöde som genereras per aktie efter att investeringar har dragits av. Detta nyckeltal är viktigt för att bedöma företagets förmåga att skapa värde för aktieägarna och finansiera utdelningar eller återköp av aktier. Högre värde är bättre."
  Kassaflode_till_Skuld_trend_ratioRank: "Kassaflöde till skuld visar företagets förmåga att betala av sina skulder med det kassaflöde som genereras från verksamheten. En hög kvot innebär att företaget snabbt kan minska sina skulder, vilket minskar den finansiella risken. Högre värde är bättre."


display_names:
  ROE: "Avkastning på eget kapital"
  ROIC: "Avkastning på investerat kapital"
  Soliditet: "Soliditet"
  Skuldsättningsgrad: "Skuldsättningsgrad"
  Räntetäckningsgrad: "Räntetäckningsgrad"
  Bruttomarginal: "Bruttomarginal"
  Rörelsemarginal: "Rörelsemarginal"
  Vinstmarginal: "Vinstmarginal"
  PE_tal: "P/E-tal"
  PB_tal: "P/B-tal"
  EV_EBITDA: "EV/EBITDA"
  Rörelseflödesmarginal: "Rörelseflödesmarginal"
  Fritt_Kassaflode_per_Aktie: "Fritt kassaflöde/aktie"
  Kassaflode_till_Skuld: "Kassaflöde/skuld"
  Basic_EPS: "Vinst/aktie (EPS)"
  Total_Revenue: "Omsättning"
  EBITDA: "EBITDA"
  pct_SMA_medium_vs_SMA_long: "SMA 50 vs 200 (%)"
  pct_SMA_short_vs_SMA_medium: "SMA 10 vs 50 (%)"
  pct_Close_vs_SMA_short: "Stängningskurs vs SMA 10 (%)"
  Trend_clusterRank: "Agg. Rank trend 4 år"
  Latest_clusterRank: "Agg. Rank sen. året"
  cagr_close: "CAGR stängningskurs"
  cagrTotal_Revenue: "CAGR omsättning"
  cagrEBITDA: "CAGR EBITDA"
  cagrBasic_EPS: "CAGR vinst/aktie"
  pct_Close_vs_SMA_short: "Stängningskurs vs SMA 10 (%)"
  pct_SMA_short_vs_SMA_medium: "SMA 10 vs 50 (%)"
  pct_SMA_medium_vs_SMA_long: "SMA 50 vs 200 (%)"
  pct_diff_short: "Delta 20 dagar (%)"
  pct_diff_medium: "Delta 90 dagar (%)"
  pct_diff_long: "Delta 200 dagar (%)"
  Kvalitet_trend_catRank: "Kvalitet trend 4 år"
  Kvalitet_latest_catRank: "Kvalitet sen. året"
  FinansiellHalsa_trend_catRank: "Finansiell Hälsa trend 4 år"
  FinansiellHalsa_latest_catRank: "Finansiell Hälsa sen. året"
  Lonsamhet_trend_catRank: "Lönsamhet trend 4 år"
  Lonsamhet_latest_catRank: "Lönsamhet sen. året"
  Vardering_trend_catRank: "Värdering trend 4 år"
  Vardering_latest_catRank: "Värdering sen. året"
  Kassaflode_trend_catRank: "Kassaflöde trend 4 år"
  Kassaflode_latest_catRank: "Kassaflöde sen. året"

tooltip_texts:
  pct_SMA_medium_vs_SMA_long: "Skillnaden mellan 50-dagars och 200-dagars glidande medelvärde i procent (senaste handelsdagen)."
  pct_SMA_short_vs_SMA_medium: "Skillnaden mellan 10-dagars och 50-dagars glidande medelvärde i procent (senaste handelsdagen)."
  pct_Close_vs_SMA_short: "Skillnaden mellan stängningskurs och 10-dagars glidande medelvärde i procent (senaste handelsdagen)."
  Trend_clusterRank: "Sammanlagd rankning av aktier baserat på **trenden** från senaste 4 årens finansiella resultat. Skala 0-100, där 100 är bäst och 0 är sämst."
  Latest_clusterRank: "Sammanlagd rankning av aktier baserat på **senaste årets** finansiella resultat. Skala 0-100, där 100 är bäst och 0 är sämst."

