# Inställningar för in- och utdata
input_ticker_file: "tickers_list.csv" # test file ends with "_test.csv" for limited set of tickers
results_file: "stock_evaluation_results.csv"
price_data_file: "price_data.csv"

# Inställningar för datainhämtning
data_fetch_years: 4 # Antal år av finansiella data som ska hämtas
data_fetch_quarterly: 5 # Antal kvartal som ska hämtas
price_data_years: 4 # Antal år av prisdata som ska hämtas

# Antal decimaler för Ranks
rank_decimals: 1

# Inställningar för glidande medelvärden
SMA_short: 10
SMA_medium: 50
SMA_long: 200

# Inställningar för pct diff från senaste slutkurs
# pct_diff_short: 20
# pct_diff_medium: 90
# pct_diff_long: 200

# CAGR inställningar
cagr_dimension:
  - "Total Revenue"
  - "Basic EPS"

# Definitioner av nyckeltal och deras källor/logik
ratio_definitions:
  ROE:
    formula: "Net_Income / Stockholders_Equity"
    source_income: ["Net Income"]
    source_bs: ["Stockholders Equity"]
    higher_is_better: True
  ROIC:
    formula: "(EBIT * (1 - (Tax_Provision / Pretax_Income))) / (Total_Debt + Stockholders_Equity)"
    source_income: ["EBIT", "Tax Provision", "Pretax Income"]
    source_bs: ["Total Debt", "Stockholders Equity"]
    higher_is_better: True
  Soliditet:
    formula: "Stockholders_Equity / Total_Assets"
    source_bs: ["Stockholders Equity", "Total Assets"]
    higher_is_better: True
  Skuldsättningsgrad:
    formula: "Total_Debt / Stockholders_Equity"
    source_bs: ["Total Debt", "Stockholders Equity"]
    higher_is_better: False
  #Räntetäckningsgrad:
    #formula: "EBIT / Interest_Expense"
    #source_income: ["EBIT", "Interest Expense"]
    #higher_is_better: True
  Bruttomarginal:
    formula: "Gross_Profit / Total_Revenue"
    source_income: ["Gross Profit", "Total Revenue"]
    higher_is_better: True
  Rörelsemarginal:
    formula: "Operating_Income / Total_Revenue"
    source_income: ["Operating Income", "Total Revenue"]
    higher_is_better: True
  Vinstmarginal:
    formula: "Net_Income / Total_Revenue"
    source_income: ["Net Income", "Total Revenue"]
    higher_is_better: True
  PE_tal:
    formula: "currentPrice / Basic_EPS"
    source_stock: ["currentPrice"]
    source_income: ["Basic EPS"]
    higher_is_better: False
  PB_tal:
    formula: "currentPrice / (Stockholders_Equity / sharesOutstanding)"
    source_stock: ["currentPrice", "sharesOutstanding"]
    source_bs: ["Stockholders Equity"]
    higher_is_better: False
  EV_EBITDA:
    formula: "(currentPrice * sharesOutstanding + Total_Debt - Cash_And_Cash_Equivalents) / EBITDA"
    source_stock: ["currentPrice", "sharesOutstanding"]
    source_bs: ["Total Debt", "Cash And Cash Equivalents"]
    source_income: ["EBITDA"]
    higher_is_better: False
  Rörelseflödesmarginal:
    formula: "Operating_Cash_Flow / Total_Revenue"
    source_cf: ["Operating Cash Flow"]
    source_income: ["Total Revenue"]
    higher_is_better: True
  #Fritt_Kassaflode_per_Aktie:
    #formula: "Free_Cash_Flow / sharesOutstanding"
    #source_cf: ["Free Cash Flow"]
    #source_stock: ["sharesOutstanding"]
    #higher_is_better: True
  Kassaflöde_till_Skuld:
    formula: "Operating_Cash_Flow / Total_Debt"
    source_cf: ["Operating Cash Flow"]
    source_bs: ["Total Debt"]
    higher_is_better: True

# Average growhth rate (AGR) inställningar
agr_dimensions:
  - "Total Revenue"
  - "Basic EPS"

kategorier:
  Kvalitet:
    - ROE
    - ROIC
  Finansiell Hälsa:
    - Soliditet
    - Skuldsättningsgrad
  Lönsamhet:
    - Bruttomarginal
    - Rörelsemarginal
    - Vinstmarginal
  Värdering:
    - PE_tal
    - PB_tal
    - EV_EBITDA
  Kassaflöde:
    - Rörelseflödesmarginal
    - Kassaflöde_till_Skuld

cluster:
  - latest
  - trend

# Ratios i kategorier
category_ratios:
  Kvalitet_latest_ratioRank:
    ROE_latest_ratioRank: 1
    ROIC_latest_ratioRank: 1
  Kvalitet_trend_ratioRank:
    ROE_trend_ratioRank: 1
    ROIC_trend_ratioRank: 1
  Kvalitet_ttm_ratioRank:
    ROE_ttm_ratioRank: 1
    ROIC_ttm_ratioRank: 1
  Finansiell_Hälsa_latest_ratioRank:
    Soliditet_latest_ratioRank: 1
    Skuldsättningsgrad_latest_ratioRank: 1
  Finansiell_Hälsa_trend_ratioRank:
    Soliditet_trend_ratioRank: 1
    Skuldsättningsgrad_trend_ratioRank: 1
  Finansiell_Hälsa_ttm_ratioRank:
    Soliditet_ttm_ratioRank: 1
    Skuldsättningsgrad_ttm_ratioRank: 1
  Lönsamhet_latest_ratioRank:
    Bruttomarginal_latest_ratioRank: 1
    Rörelsemarginal_latest_ratioRank: 1
    Vinstmarginal_latest_ratioRank: 1
  Lönsamhet_trend_ratioRank:
    Bruttomarginal_trend_ratioRank: 1
    Rörelsemarginal_trend_ratioRank: 1
    Vinstmarginal_trend_ratioRank: 1
  Lönsamhet_ttm_ratioRank:
    Bruttomarginal_ttm_ratioRank: 1
    Rörelsemarginal_ttm_ratioRank: 1
    Vinstmarginal_ttm_ratioRank: 1
  Värdering_latest_ratioRank:
    PE_tal_latest_ratioRank: 1
    PB_tal_latest_ratioRank: 1
    EV_EBITDA_latest_ratioRank: 1
  Värdering_trend_ratioRank:
    PE_tal_trend_ratioRank: 1
    PB_tal_trend_ratioRank: 1
    EV_EBITDA_trend_ratioRank: 1
  Värdering_ttm_ratioRank:
    PE_tal_ttm_ratioRank: 1
    PB_tal_ttm_ratioRank: 1
    EV_EBITDA_ttm_ratioRank: 1
  Kassaflöde_latest_ratioRank:
    Rörelseflödesmarginal_latest_ratioRank: 1
    Kassaflöde_till_Skuld_latest_ratioRank: 1
  Kassaflöde_trend_ratioRank:
    Rörelseflödesmarginal_trend_ratioRank: 1
    Kassaflöde_till_Skuld_trend_ratioRank: 1
  Kassaflöde_ttm_ratioRank:
    Rörelseflödesmarginal_ttm_ratioRank: 1
    Kassaflöde_till_Skuld_ttm_ratioRank: 1

# Hjälptexter för nyckeltal (endast _latest_rank)
ratio_help_texts:

  ROE_latest: "Avkastning på eget kapital (ROE) visar hur effektivt bolaget genererar vinst på aktieägarnas kapital under det senaste året. Ett högt ROE för det senaste året indikerar att företaget har varit framgångsrikt med att skapa vinst från aktieägarnas satsade kapital just nu. Jämför gärna med branschkollegor för att få en aktuell bild av lönsamheten."
  ROIC_latest: "Avkastning på investerat kapital (ROIC) mäter hur väl bolaget har använt både eget och lånat kapital för att skapa vinst under det senaste året. Ett högt ROIC för året visar att företaget har varit effektivt på att generera avkastning på det totala kapitalet i den senaste perioden."
  Soliditet_latest: "Soliditet visar hur stor andel av tillgångarna som är finansierade med eget kapital just nu. En hög soliditet för det senaste året innebär att företaget har en stark finansiell ställning och är mindre beroende av lån, vilket minskar den finansiella risken på kort sikt."
  Skuldsättningsgrad_latest: "Skuldsättningsgrad visar förhållandet mellan företagets skulder och eget kapital under det senaste året. En låg skuldsättningsgrad för året innebär att företaget har relativt lite skulder jämfört med sitt egna kapital, vilket minskar risken för betalningsproblem just nu."
  Räntetäckningsgrad_latest: "Räntetäckningsgrad visar företagets förmåga att täcka sina räntekostnader med rörelseresultatet (EBIT) under det senaste året. En hög räntetäckningsgrad för året innebär att företaget har god marginal för att betala sina räntekostnader just nu."
  Bruttomarginal_latest: "Bruttomarginal visar hur stor andel av omsättningen som återstår efter att produktionskostnaderna har dragits av under det senaste året. En hög bruttomarginal för året innebär att företaget har god kontroll över sina direkta kostnader och kan generera mer vinst från varje såld enhet just nu."
  Rörelsemarginal_latest: "Rörelsemarginal visar hur stor andel av omsättningen som återstår efter att alla rörelsekostnader har dragits av under det senaste året. En hög rörelsemarginal för året indikerar att företaget har varit effektivt på att kontrollera sina kostnader och generera vinst från den löpande verksamheten just nu."
  Vinstmarginal_latest: "Vinstmarginal visar hur stor andel av omsättningen som blir kvar som vinst efter alla kostnader, inklusive skatt och räntor, under det senaste året. En hög vinstmarginal för året innebär att företaget har varit bra på att omvandla försäljning till vinst just nu."
  PE_tal_latest: "P/E-tal (pris/vinst-tal) visar hur aktien värderas i förhållande till företagets vinst per aktie för det senaste året. Ett lågt P/E-tal kan tyda på att aktien är lågt värderad just nu, men det kan också bero på tillfälligt låg vinst. Jämför med liknande företag för att få en aktuell värdering."
  PB_tal_latest: "P/B-tal (pris/eget kapital-tal) visar hur aktien värderas i förhållande till företagets egna kapital per aktie för det senaste året. Ett lågt P/B-tal kan indikera att aktien är undervärderad just nu, men det kan också bero på problem i verksamheten. Jämför alltid med branschkollegor för att få en rättvisande bild."
  EV_EBITDA_latest: "EV/EBITDA (företagsvärde/rörelseresultat före avskrivningar) visar bolagets värdering i förhållande till dess rörelseresultat före avskrivningar för det senaste året. Ett lågt EV/EBITDA-tal kan tyda på att bolaget är lågt värderat just nu i förhållande till sin intjäningsförmåga."
  Rörelseflödesmarginal_latest: "Rörelseflödesmarginal visar hur stor andel av omsättningen som omvandlas till kassaflöde från den löpande verksamheten under det senaste året. En hög rörelseflödesmarginal för året innebär att företaget har varit bra på att generera kassaflöde från sin försäljning just nu."
  Fritt_Kassaflode_per_Aktie_latest: "Fritt kassaflöde per aktie visar hur mycket kassaflöde som genereras per aktie efter att investeringar har dragits av under det senaste året. Detta nyckeltal är viktigt för att bedöma företagets förmåga att skapa värde för aktieägarna just nu."
  Kassaflöde_till_Skuld_latest: "Kassaflöde till skuld visar företagets förmåga att betala av sina skulder med det kassaflöde som genereras från verksamheten under det senaste året. En hög kvot för året innebär att företaget snabbt kan minska sina skulder just nu."


  ROE_trend: "Avkastning på eget kapital (ROE) visar om bolaget har förbättrat sin förmåga att skapa vinst på aktieägarnas kapital under de senaste fyra åren. Ett högre trendvärde indikerar att ROE har ökat och att bolagets lönsamhet har stärkts över tid."
  ROIC_trend: "Avkastning på investerat kapital (ROIC) visar om bolaget har blivit bättre på att använda sitt kapital för att skapa vinst under de senaste fyra åren. Ett högre trendvärde innebär att ROIC har förbättrats och att bolaget har blivit mer effektivt över tid."
  Soliditet_trend: "Soliditetstrenden visar om bolaget har ökat andelen eget kapital i förhållande till tillgångarna under de senaste fyra åren. Ett högre trendvärde innebär att bolaget har stärkt sin finansiella ställning och minskat sin risk över tid."
  Skuldsättningsgrad_trend: "Skuldsättningsgradstrenden visar om bolaget har minskat sina skulder i förhållande till eget kapital under de senaste fyra åren. Ett lägre trendvärde innebär att skuldsättningen har minskat och att den finansiella risken har blivit lägre över tid."
  Räntetäckningsgrad_trend: "Räntetäckningsgradstrenden visar om bolaget har förbättrat sin förmåga att täcka räntekostnader med rörelseresultatet (EBIT) under de senaste fyra åren. Ett högre trendvärde innebär att marginalen har ökat och att bolaget har blivit mer motståndskraftigt mot räntekostnader över tid."
  Bruttomarginal_trend: "Bruttomarginalstrenden visar om bolaget har ökat sin förmåga att behålla vinst efter produktionskostnader under de senaste fyra åren. Ett högre trendvärde innebär att bruttomarginalen har förbättrats och att bolaget har blivit mer lönsamt över tid."
  Rörelsemarginal_trend: "Rörelsemarginalstrenden visar om bolaget har blivit bättre på att kontrollera sina rörelsekostnader och öka vinsten under de senaste fyra åren. Ett högre trendvärde innebär att rörelsemarginalen har ökat och att bolaget har blivit mer effektivt över tid."
  Vinstmarginal_trend: "Vinstmarginalstrenden visar om bolaget har ökat sin förmåga att omvandla omsättning till vinst under de senaste fyra åren. Ett högre trendvärde innebär att vinstmarginalen har förbättrats och att bolaget har blivit mer lönsamt över tid."
  PE_tal_trend: "P/E-talstrenden visar om aktien har blivit billigare eller dyrare i förhållande till vinst per aktie under de senaste fyra åren. Ett lägre trendvärde innebär att aktien har blivit billigare över tid, medan ett högre värde kan tyda på ökad värdering."
  PB_tal_trend: "P/B-talstrenden visar om aktien har blivit mer eller mindre attraktiv i förhållande till eget kapital per aktie under de senaste fyra åren. Ett lägre trendvärde innebär att aktien har blivit mer attraktivt värderad över tid."
  EV_EBITDA_trend: "EV/EBITDA-trenden visar om bolaget har blivit mer eller mindre attraktivt värderat i förhållande till rörelseresultat före avskrivningar under de senaste fyra åren. Ett lägre trendvärde innebär att bolaget har blivit mer attraktivt värderat över tid."
  Rörelseflödesmarginal_trend: "Rörelseflödesmarginalstrenden visar om bolaget har förbättrat sin förmåga att omvandla omsättning till kassaflöde under de senaste fyra åren. Ett högre trendvärde innebär att kassaflödesgenereringen har ökat över tid."
  Fritt_Kassaflode_per_Aktie_trend: "Trenden för fritt kassaflöde per aktie visar om bolaget har blivit bättre på att skapa kassaflöde till aktieägarna under de senaste fyra åren. Ett högre trendvärde innebär att bolaget har förbättrat sin kassaflödesgenerering över tid."
  Kassaflöde_till_Skuld_trend: "Trenden för kassaflöde till skuld visar om bolaget har blivit bättre på att betala av sina skulder med kassaflöde från verksamheten under de senaste fyra åren. Ett högre trendvärde innebär att bolaget har förbättrat sin skuldsituation över tid."


display_names:
  ROE: "Avkastning på eget kapital"
  ROIC: "Avkastning på investerat kapital"
  Soliditet: "Soliditet"
  Skuldsättningsgrad: "Skuldsättningsgrad"
  Räntetäckningsgrad: "Räntetäckningsgrad"
  Bruttomarginal: "Bruttomarginal"
  Rörelsemarginal: "Rörelsemarginal"
  Vinstmarginal: "Vinstmarginal"
  PE_tal: "P/E-tal"
  PB_tal: "P/B-tal"
  EV_EBITDA: "EV/EBITDA"
  Rörelseflödesmarginal: "Rörelseflödesmarginal"
  Fritt_Kassaflode_per_Aktie: "Fritt kassaflöde/aktie"
  Kassaflode_till_Skuld: "Kassaflöde/skuld"
  Basic_EPS: "Vinst/aktie (EPS)"
  Total_Revenue: "Omsättning"
  EBITDA: "EBITDA"
  pct_SMA_medium_vs_SMA_long: "SMA 50 vs 200 (%)"
  pct_SMA_short_vs_SMA_medium: "SMA 10 vs 50 (%)"
  pct_Close_vs_SMA_short: "Pris vs SMA 10 (%)"
  Trend_clusterRank: "Agg. Rank trend 4 år"
  Latest_clusterRank: "Agg. Rank sen. året"
  TTM_clusterRank: "Agg. Rank ttm diff"
  cagr_close: "CAGR Aktiekurs"
  cagrTotal_Revenue: "CAGR omsättning"
  cagrBasic_EPS: "CAGR vinst/aktie"
  pct_SMA_short_vs_SMA_medium: "SMA 10 vs 50 (%)"
  pct_SMA_medium_vs_SMA_long: "SMA 50 vs 200 (%)"
  pct_diff_short: "Delta 20 dagar (%)"
  pct_diff_medium: "Delta 90 dagar (%)"
  pct_diff_long: "Delta 200 dagar (%)"
  Kvalitet_trend_catRank: "Kvalitet trend 4 år"
  Kvalitet_latest_catRank: "Kvalitet sen. året"
  Kvalitet_ttm_catRank: "Kvalitet ttm diff"
  Finansiell_Hälsa_trend_catRank: "Finansiell Hälsa trend 4 år"
  Finansiell_Hälsa_latest_catRank: "Finansiell Hälsa sen. året"
  Finansiell_Hälsa_ttm_catRank: "Finansiell Hälsa ttm diff"
  Lönsamhet_trend_catRank: "Lönsamhet trend 4 år"
  Lönsamhet_latest_catRank: "Lönsamhet sen. året"
  Lönsamhet_ttm_catRank: "Lönsamhet ttm diff"
  Värdering_trend_catRank: "Värdering trend 4 år"
  Värdering_latest_catRank: "Värdering sen. året"
  Värdering_ttm_catRank: "Värdering ttm diff"
  Kassaflöde_trend_catRank: "Kassaflöde trend 4 år"
  Kassaflöde_latest_catRank: "Kassaflöde sen. året"
  Kassaflöde_ttm_catRank: "Kassaflöde ttm diff"
  Kvalitet: "Kvalitet"
  FinansiellHalsa: "Finansiell Hälsa"
  Lonsamhet: "Lönsamhet"
  Vardering: "Värdering"
  Kassaflode: "Kassaflöde"
  SMA_short: "SMA 10"
  SMA_medium: "SMA 50"
  SMA_long: "SMA 200"
  cagrTotal_Revenue: "Omsättning trend 4 år"
  cagrBasic_EPS: "Vinst/aktie trend 4 år"
  Total_Revenue_AvgGrowth_Rank: "Rank Omsättning tillväxt"
  Basic_EPS_AvgGrowth_Rank: "Rank Vinst/aktie tillväxt"
  Dividend_AvgGrowth_Rank: "Rank Utdelning tillväxt"
  Total_Revenue_AvgGrowth: "Omsättning tillväxt"
  Basic_EPS_AvgGrowth: "Vinst/aktie tillväxt"
  Dividend_AvgGrowth: "Utdelning tillväxt"

tooltip_texts:
  pct_SMA_medium_vs_SMA_long: "Skillnaden mellan 50-dagars och 200-dagars glidande medelvärde i procent (senaste handelsdagen). Ett positivt värde indikerar att den kortare medelvärdesperioden ligger över den längre, vilket ofta ses som ett styrketecken i aktiens trend."
  pct_SMA_short_vs_SMA_medium: "Skillnaden mellan 10-dagars och 50-dagars glidande medelvärde i procent (senaste handelsdagen). Ett positivt värde kan tyda på att aktien har en kortsiktig uppåtgående trend."
  pct_Close_vs_SMA_short: "Skillnaden mellan stängningskurs och 10-dagars glidande medelvärde i procent (senaste handelsdagen). Ett positivt värde innebär att aktien handlas över sitt kortsiktiga medelvärde, vilket kan signalera styrka."
  Trend_clusterRank: "Sammanlagd rankning av aktier baserat på **trenden** från senaste 4 årens finansiella resultat. Skala 0-100, där 100 är bäst och 0 är sämst. Högre värde indikerar att bolaget har haft en positiv utveckling över tid inom flera nyckeltal."
  Latest_clusterRank: "Sammanlagd rankning av aktier baserat på **senaste årets** finansiella resultat. Skala 0-100, där 100 är bäst och 0 är sämst. Högre värde visar att bolaget presterar starkt just nu inom flera nyckeltal."
  TTM_clusterRank: "Sammanlagd rankning av aktier baserat på **ttm (trailing twelve months)** finansiella resultat jämfört med senaste årsresultat. Skala 0-100, där 100 är bäst och 0 är sämst. Högre värde indikerar att bolaget har en stark prestation sedan senaste årsrapport."
  cagrTotal_Revenue: "Rankning av omsättningens trend över de senaste 4 åren. Ett högt värde indikerar att bolaget har haft en stabil och positiv tillväxt i omsättningen."
  cagrBasic_EPS: "Rankning av vinst per aktie (EPS) trend över de senaste 4 åren. Ett högt värde visar att bolaget har haft en god och växande lönsamhet per aktie över tid."
  "Total_Revenue_AvgGrowth_Rank": "Rankning av genomsnittlig tillväxttakt för omsättningen över de senaste 4 åren."
  "Basic_EPS_AvgGrowth_Rank": "Rankning av genomsnittlig tillväxttakt för vinst per aktie (EPS) över de senaste 4 åren."
  "Dividend_AvgGrowth_Rank": "Rankning av genomsnittlig tillväxttakt för utdelningen över de senaste 4 åren."
  "Viktning för Trend (%)": "Viktning av **trend över de senaste 4 åren** i den övergripande rankningen."
  "Viktning för Senaste (%)": "Viktning av **senaste årets resultat** i den övergripande rankningen."
  "Viktning för TTM (%)": "Viktning av **TTM-förändring** jämfört med senaste årsresultat i den övergripande rankningen. (Trailing Twelve Months, TTM)"

color_ranges:
  - range: [0, 20]
    color: "#ffcccc"
  - range: [20, 40]
    color: "#ffe5cc"
  - range: [40, 60]
    color: "#ffffcc"
  - range: [60, 80]
    color: "#e6ffe6"
  - range: [80, 100]
    color: "#ccffcc"
