name: Daily Stock Data Update

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 06:00 UTC every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Install dependencies
      run: uv pip install --system -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run stock analyzer
      run: uv run python stock_analyzer.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*
        git commit -m "Update stock data $(date +%Y%m%d)" || echo "No changes to commit"
        git push