name: Daily Stock Data Update

on:
  schedule:
    - cron: '0 5 * * 2-6'  # Run at 05:00 UTC Tuesday through Saturday
  workflow_dispatch:  # Allow manual trigger

env:
  ENVIRONMENT: remote

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: '0.4.18'
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    
    - name: Verify dependencies
      run: |
        source .venv/bin/activate
        pip list
        python -c "import pandas; import yfinance; import finta; import yaml; import requests; import bs4; print('Dependencies verified')"
    
    - name: Create data and tickers directories
      run: |
        mkdir -p data/remote
    
    - name: Run ticker scraper
      run: |
        source .venv/bin/activate
        uv run python scrape_tickers.py > scrape_tickers.log 2>&1
    
    - name: Run stock analyzer
      run: |
        source .venv/bin/activate
        uv run python rank.py > rank.log 2>&1
    
    - name: Commit and push updated data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add data/remote/*
        git diff --staged --quiet || git commit -m "Update stock data and tickers $(date -u +%Y-%m-%d)"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: |
          scrape_tickers.log
          rank.log