name: Weekly Fundamentals Trend Update

on:
  #schedule:
  #  - cron: '0 8 * * 0'  # Run at 08:00 UTC every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-fundamentals-trend:
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: '0.4.18'

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Create data and tickers directories
      run: |
        mkdir -p balance
        mkdir -p cashflow
        mkdir -p income

    - name: Run fundamentals trend script
      run: |
        source .venv/bin/activate
        uv run python fundamentals_trend.py > fundamentals_trend.log 2>&1

    - name: Commit and push updated fundamentals trend data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add fundamentals_trend.csv
        if ! git diff --staged --quiet; then
          git commit -m "Update fundamentals trend data $(date -u +%Y-%m-%d)"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
        fi

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: |
          fundamentals_trend.log